# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3aab1665715dd03b4f60b5bc21a108b1e3dacdbbd706114f95f38bb492af17864fda485cd5f5c54b97dfd812b5fb7e25af3057263a668f8945eb8d4706bf8314

test:
  secret_key_base: b60921c072413e42366e03cc6ca22e9e9debec55bd5bafe8ef6335f0a88ef7ee80ae0bd1e6e044ae88897cf9f23cae68a7b08b9126b92e061e41cc574da65cfa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
